### ISSUE TITLE
Weird output, using weights from repo

### ISSUE THREAD

**Issue by kexinhuang12345** [yashk2810/Image-Captioning#1]
Hi there,

Thank you so much for the Jupyter version of image captioning! 

I wanted to use your pre-trained model to generate captions. So I skipped the parts that you generated weights and loaded the weights in the repository. But the output captions look really weird like this:

<img width="1004" alt="2017-12-03 9 12 54" src="https://user-images.githubusercontent.com/27795075/33533763-2ed47806-d871-11e7-9f12-059b44b1c58b.png">

I got a warning about keras merge algorithm:

<img width="1016" alt="2017-12-03 9 32 16" src="https://user-images.githubusercontent.com/27795075/33533814-7c6fc354-d871-11e7-82ed-3fd4b387cd41.png">

does this have to do with the weird output?

I am a beginner in deep learning and I am trying to use captions for any given images for my final project in NLP class. Any suggestions would be welcomed! 

Thanks!!!

**Comment by yashk2810** [comment]
If you are creating your own unique dictionary instead of using mine, then this error might occur. The warning is occurring because I was using an older version of Keras. It has nothing to do with the error. Try using my unique.p file and see if the error goes away.

**Comment by kexinhuang12345** [comment]
Thanks for your reply! I tried using your unique.p file. The output changes but is still pretty weird. 
<img width="918" alt="2017-12-04 11 03 55" src="https://user-images.githubusercontent.com/27795075/33589603-94030086-d947-11e7-8916-b1f97aa3d2ac.png">
Does it have something to do with python version? Because I am using Python 2 and I transferred your unique.p from protocol 3 to 2. 

Just to clarify, in order to get the same results, I only need to skip the training parts and load the unique.p files and weights you provide right? 

Thank you soo much!!!

**Comment by yashk2810** [comment]
Yup, you can skip the training part and just load the weights. When I tried it on my computer it works perfectly. Let me recreate the error on my machine and get back to you.

**Comment by kexinhuang12345** [comment]
Perfect! Thank you sooo much! Do you want my version of jupyter notebook, if it helps to facilitate the process?

**Comment by yashk2810** [comment]
Yup, that will be helpful.

**Comment by kexinhuang12345** [comment]
Hi just sent it to your email as i couldn't post jupyter notebook here. Also, I noticed the order of the flickr8 datasets (which I downloaded from the link in your blog) is different from yours to mine, does it have something to do with the error as the encoded image file is different?

**Comment by kexinhuang12345** [comment]
Hi Yash, sorry to bother you again. I tried to see where it went wrong for the last two days, but still, nothing had changed. Any finding on your side? Really appreciate it!

**Comment by yashk2810** [comment]
I have my exams going on. I will get back to you in a couple of days. Sorry for the wait.

**Comment by kexinhuang12345** [comment]
Sure, Thank you!

**Comment by ayushpatel567** [comment]
I am also getting the similar weird output of some .. and some letters,Any help?
